### ISSUE TITLE
tried to install, but fails to load in py3 env

### ISSUE THREAD

**Issue by hemna** [Granitosaurus/xonsh-click-tabcomplete#3]
╰─>$ xontrib load click_tabcomplete
<unknown>:1: DeprecationWarning: invalid escape sequence \w
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
AssertionError
Failed to load xontrib click_tabcomplete.

**Comment by hemna** [comment]
```
╭─waboring(xonsh) at dl360-1 in ~/devel/aprsd tcpkiss|…6⚑7
╰─$ xontrib load click_tabcomplete
<unknown>:1: DeprecationWarning: invalid escape sequence \w
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/waboring/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 89, in xontribs_load
    update_context(name, ctx=ctx)
  File "/home/waboring/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 72, in update_context
    modctx = xontrib_context(name)
  File "/home/waboring/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 37, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/xontrib/click_tabcomplete.xsh", line 2, in <module>
    _ALL_PACKAGES = [(p.key, ','.join(req.name for req in p.requires())) for p in _pip.get_installed_distributions()]
AttributeError: module 'pip' has no attribute 'get_installed_distributions'
Failed to load xontrib click_tabcomplete.
```

```
╭─waboring(xonsh) at dl360-1 in ~/devel/aprsd tcpkiss|…6⚑7
╰─$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.26               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.16               |
| shell type       | prompt_toolkit       |
| pygments         | 2.8.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | abbrevs              |
| xontrib 2        | autovox              |
| xontrib 3        | autoxsh              |
| xontrib 4        | avox                 |
| xontrib 5        | avox_poetry          |
| xontrib 6        | back2dir             |
| xontrib 7        | cmd_done             |
| xontrib 8        | commands             |
| xontrib 9        | coreutils            |
| xontrib 10       | direnv               |
| xontrib 11       | docker_tabcomplete   |
| xontrib 12       | fzf-widgets          |
| xontrib 13       | gitinfo              |
| xontrib 14       | histcpy              |
| xontrib 15       | vox                  |
| xontrib 16       | voxapi               |
| xontrib 17       | z                    |
+------------------+----------------------+
```
